<<<<<<< HEAD
version: "2.1"
services:
  marquez_db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=buendia
      - MARQUEZ_PASSWORD=macondo
    volumes:
      - ./docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  marquez:
    image: quay.io/wework/marquez:latest
=======
version: "3.7"
services:
  marquez_web:
    build: .
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - marquez

  seed_marquez_db:
    build: ./docker/db
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
    depends_on:
      - marquez

  marquez:
    image: marquezproject/marquez:latest
>>>>>>> upstream/master
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
      - MARQUEZ_CONFIG=/usr/src/app/config.yml
      - POSTGRES_HOST=marquez_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=marquez
      - POSTGRES_USER=buendia
      - POSTGRES_PASSWORD=macondo
<<<<<<< HEAD
      # - CAYLEY_HOST=cayley
      # - CAYLEY_PORT=64210
    restart: always
=======
>>>>>>> upstream/master
    volumes:
      - ./docker/marquez.yml:/usr/src/app/config.yml
    depends_on:
      - marquez_db
<<<<<<< HEAD
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/ping"]
      interval: 30s
      timeout: 2s
      retries: 5

  # cayley:
  #   image: 'quay.io/wework/marquez-cayley:0.7.5.20190821.2582bd8'
  #   ports:
  #     - '64210:64210'
  #   environment:
  #     - CAYLEY_CFG=/data/cayley.yml
  #     - POSTGRES_HOST=marquez_db:5432
  #     - POSTGRES_DB=marquez
  #     - POSTGRES_USER=buendia
  #     - POSTGRES_PASSWORD=macondo
  #   restart: always
  #   volumes:
  #     - ./docker/cayley.yml:/data/cayley.yml
  #   depends_on:
  #     marquez:
  #       condition: service_healthy

  seed_marquez_db:
    build: ./docker/db
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
    depends_on:
      marquez:
        condition: service_healthy

  marquez_web:
    build: .
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_HOST=marquez
    ports:
      - "3000:3000"
    depends_on:
      - marquez
=======

  marquez_db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=buendia
      - MARQUEZ_PASSWORD=macondo
    volumes:
      - ./docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
>>>>>>> upstream/master
