version: "3.7"
services:
  marquez_web:
    build: .
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - marquez

  seed_marquez_db:
    build: ./docker/db
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
    depends_on:
      - marquez

  marquez:
    image: marquezproject/marquez:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
      - MARQUEZ_CONFIG=/usr/src/app/config.yml
      - POSTGRES_HOST=marquez_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=marquez
      - POSTGRES_USER=buendia
      - POSTGRES_PASSWORD=macondo
    volumes:
      - ./docker/marquez.yml:/usr/src/app/config.yml
    depends_on:
      - marquez_db

  marquez_db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=buendia
      - MARQUEZ_PASSWORD=macondo
    volumes:
      - ./docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
