version: 2

deploy_context: &deploy_context
  context: org-global
  filters:
    tags:
      only: /^[0-9]+(\.[0-9]+){2}\.([0-9]){4}([0-9]){2}([0-9]){2}\.([0-9a-f]){7}$/ # X.Y.Z.YYYMMDD.SHA-1
    branches:
      ignore: /.*/

wek8s_deploy: &wek8s_deploy
  docker:
    - image: quay.io/wework/wek8s-tools:0.2
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASSWD
  working_directory: ~/marquez-web

jobs:
  test:
    docker:
      - image: circleci/node:11.9.0
    working_directory: ~/marquez-web
    environment:
      TZ: 'America/New_York'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ .Revision }}
            - v1-deps-{{ .Branch }}
      - run: npm install
      - run: npm run test
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ .Branch }}-{{ .Revision }}

  release:
    machine: true
    working_directory: ~/marquez-web
    steps:
      - checkout
      - run: .circleci/get-docker.sh
      - run: ./docker/login.sh
      - run: ./docker/build-and-push.sh $CIRCLE_TAG

<<<<<<< HEAD
  wek8s_phoenix:
    <<: *wek8s_deploy
    steps:
      - checkout
      - run: ./.circleci/deploy.sh -v $CIRCLE_TAG

  wek8s_kraken:
    <<: *wek8s_deploy
    steps:
      - checkout
      - run: ./.circleci/deploy.sh -p -v $CIRCLE_TAG

=======
>>>>>>> upstream/master
workflows:
  version: 2
  marquez_web:
    jobs:
      - test
<<<<<<< HEAD

  deploy:
    jobs:
      - release:
          <<: *deploy_context
      - wek8s_phoenix:
          requires:
            - release
          <<: *deploy_context
      - wek8s_kraken_approval:
          type: approval
          requires:
            - wek8s_phoenix
          <<: *deploy_context
      - wek8s_kraken:
          requires:
            - wek8s_kraken_approval
          <<: *deploy_context
=======
      - release:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              ignore: /.*/
>>>>>>> upstream/master
