server:
  applicationConnectors:
  - type: http
    port: ${MARQUEZ_PORT:-8080}
  adminConnectors:
  - type: http
    port: ${MARQUEZ_ADMIN_PORT:-8081}

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

# cayley:
#   host: ${CAYLEY_HOST:-localhost}
#   port: ${CAYLEY_PORT:-64210}

logging:
  level: ${LOG_LEVEL:-INFO}
  appenders:
    - type: console
