# Default values for generic_service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: marquez-web
namespace: dataplatform

releaseVersion: 1.0.0

replicaCount: 3

command:
  - npm
args:
  - start

healthProbe:
  http:
    enabled: true
    path: /hello

image:
  repository: quay.io/wework/marquez-web
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    - port: 3000
      containerPort: 3000
      name: http
      protocol: TCP

ingress:
  enabled: true
  port: 3000
  annotations:
    kubernetes.io/ingress.class: nginx-external
    nginx.org/server-snippet: "proxy_ssl_verify off;"
  path: /

monitoring:
  enabled: false
  team: dataplatform
  servicePortName: http

vault:
  enabled: true

envVars:
  - Name: MARQUEZ_SERVICE_HOST
    Value: marquez-service

  - Name: MARQUEZ_SERVICE_PORT
    Value: 5000